### ISSUE TITLE
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

### ISSUE THREAD

**Issue by betanyeli** [betanyeli/BB-MdLinks#2]
Mi función readRoute me está presentando el siguiente error.
`Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
`
![issue](https://user-images.githubusercontent.com/48498105/60541586-ea0ef680-9cdf-11e9-8ceb-945186303a88.JPG)

Además que me lanza como uncovered lines la parte de los catch y rejects de las funciones con promesas! 
Y encontré esto: https://jestjs.io/docs/en/troubleshooting#unresolved-promises

¿Alguna sugerencia?
@laboratoria @MarinesLemus007

**Comment by MarinesLemus007** [comment]
Interesante

**Comment by MarinesLemus007** [comment]
Aún más interesante
